name: "multieventpipeline"

on: 
  push:
    branches:
      - master
      - production

jobs:
  on-push:
    runs-on: ubuntu-latest
    steps:
      - name: "Running on master push"
        run: echo "hello world" 