name: multi_event_pipeline
on:
  push: 
    branches:
      - master
      - production
  
  pull_request:
    branches:
      - master
      - production
    types:
      - opened
      - closed
  
  workflow_dispatch:

jobs:
  on-push:   #job1 name
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: "Running on master/production push branches "
        run: echo "Push Successfull"
  
  on-pull_request-opened:
    if: github.event_name == 'pull_request' && github.event_action == 'opened'
    runs-on: ubuntu-latest
    steps:
      - name: "Running on pull request opened "
        run: echo "Pull is going"
  
  on-pull_request-closed:
    if: github.event_name == 'pull_request' && github.event_action == 'closed'
    runs-on: ubuntu-latest
    steps:
      - name: "Running on pull request closed "
        run: echo "Pull is successfull"
  

